/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  AuthUserEnvelope,
  BeginBrowserLoginParams,
  HandleBrowserLoginCallbackParams,
  HealthStatus,
  HelpRequest,
  HelpResponse,
  LogoutSuccess,
  MobileTokenExchangeRequest,
  MobileTokenExchangeSuccess,
  UpdateProfileBody,
  UsageStatus,
  UserProfile,
} from "./api.schemas";

import { customFetch } from "../custom-fetch";
import type { ErrorType, BodyType } from "../custom-fetch";

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Returns server health status
 * @summary Health check
 */
export const getHealthCheckUrl = () => {
  return `/api/healthz`;
};

export const healthCheck = async (
  options?: RequestInit,
): Promise<HealthStatus> => {
  return customFetch<HealthStatus>(getHealthCheckUrl(), {
    ...options,
    method: "GET",
  });
};

export const getHealthCheckQueryKey = () => {
  return [`/api/healthz`] as const;
};

export const getHealthCheckQueryOptions = <
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getHealthCheckQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof healthCheck>>> = ({
    signal,
  }) => healthCheck({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type HealthCheckQueryResult = NonNullable<
  Awaited<ReturnType<typeof healthCheck>>
>;
export type HealthCheckQueryError = ErrorType<unknown>;

/**
 * @summary Health check
 */

export function useHealthCheck<
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getHealthCheckQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get the currently authenticated user
 */
export const getGetCurrentAuthUserUrl = () => {
  return `/api/auth/user`;
};

export const getCurrentAuthUser = async (
  options?: RequestInit,
): Promise<AuthUserEnvelope> => {
  return customFetch<AuthUserEnvelope>(getGetCurrentAuthUserUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetCurrentAuthUserQueryKey = () => {
  return [`/api/auth/user`] as const;
};

export const getGetCurrentAuthUserQueryOptions = <
  TData = Awaited<ReturnType<typeof getCurrentAuthUser>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getCurrentAuthUser>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetCurrentAuthUserQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getCurrentAuthUser>>
  > = ({ signal }) => getCurrentAuthUser({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getCurrentAuthUser>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetCurrentAuthUserQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCurrentAuthUser>>
>;
export type GetCurrentAuthUserQueryError = ErrorType<unknown>;

/**
 * @summary Get the currently authenticated user
 */

export function useGetCurrentAuthUser<
  TData = Awaited<ReturnType<typeof getCurrentAuthUser>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getCurrentAuthUser>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetCurrentAuthUserQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Start the browser OIDC login flow
 */
export const getBeginBrowserLoginUrl = (params?: BeginBrowserLoginParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/login?${stringifiedParams}`
    : `/api/login`;
};

export const beginBrowserLogin = async (
  params?: BeginBrowserLoginParams,
  options?: RequestInit,
): Promise<unknown> => {
  return customFetch<unknown>(getBeginBrowserLoginUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getBeginBrowserLoginQueryKey = (
  params?: BeginBrowserLoginParams,
) => {
  return [`/api/login`, ...(params ? [params] : [])] as const;
};

export const getBeginBrowserLoginQueryOptions = <
  TData = Awaited<ReturnType<typeof beginBrowserLogin>>,
  TError = ErrorType<void>,
>(
  params?: BeginBrowserLoginParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof beginBrowserLogin>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getBeginBrowserLoginQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof beginBrowserLogin>>
  > = ({ signal }) => beginBrowserLogin(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof beginBrowserLogin>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type BeginBrowserLoginQueryResult = NonNullable<
  Awaited<ReturnType<typeof beginBrowserLogin>>
>;
export type BeginBrowserLoginQueryError = ErrorType<void>;

/**
 * @summary Start the browser OIDC login flow
 */

export function useBeginBrowserLogin<
  TData = Awaited<ReturnType<typeof beginBrowserLogin>>,
  TError = ErrorType<void>,
>(
  params?: BeginBrowserLoginParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof beginBrowserLogin>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getBeginBrowserLoginQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Complete the browser OIDC login flow
 */
export const getHandleBrowserLoginCallbackUrl = (
  params?: HandleBrowserLoginCallbackParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/callback?${stringifiedParams}`
    : `/api/callback`;
};

export const handleBrowserLoginCallback = async (
  params?: HandleBrowserLoginCallbackParams,
  options?: RequestInit,
): Promise<unknown> => {
  return customFetch<unknown>(getHandleBrowserLoginCallbackUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getHandleBrowserLoginCallbackQueryKey = (
  params?: HandleBrowserLoginCallbackParams,
) => {
  return [`/api/callback`, ...(params ? [params] : [])] as const;
};

export const getHandleBrowserLoginCallbackQueryOptions = <
  TData = Awaited<ReturnType<typeof handleBrowserLoginCallback>>,
  TError = ErrorType<void>,
>(
  params?: HandleBrowserLoginCallbackParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof handleBrowserLoginCallback>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getHandleBrowserLoginCallbackQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof handleBrowserLoginCallback>>
  > = ({ signal }) =>
    handleBrowserLoginCallback(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof handleBrowserLoginCallback>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type HandleBrowserLoginCallbackQueryResult = NonNullable<
  Awaited<ReturnType<typeof handleBrowserLoginCallback>>
>;
export type HandleBrowserLoginCallbackQueryError = ErrorType<void>;

/**
 * @summary Complete the browser OIDC login flow
 */

export function useHandleBrowserLoginCallback<
  TData = Awaited<ReturnType<typeof handleBrowserLoginCallback>>,
  TError = ErrorType<void>,
>(
  params?: HandleBrowserLoginCallbackParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof handleBrowserLoginCallback>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getHandleBrowserLoginCallbackQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Clear the session and begin OIDC logout
 */
export const getLogoutBrowserSessionUrl = () => {
  return `/api/logout`;
};

export const logoutBrowserSession = async (
  options?: RequestInit,
): Promise<unknown> => {
  return customFetch<unknown>(getLogoutBrowserSessionUrl(), {
    ...options,
    method: "GET",
  });
};

export const getLogoutBrowserSessionQueryKey = () => {
  return [`/api/logout`] as const;
};

export const getLogoutBrowserSessionQueryOptions = <
  TData = Awaited<ReturnType<typeof logoutBrowserSession>>,
  TError = ErrorType<void>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof logoutBrowserSession>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getLogoutBrowserSessionQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof logoutBrowserSession>>
  > = ({ signal }) => logoutBrowserSession({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof logoutBrowserSession>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type LogoutBrowserSessionQueryResult = NonNullable<
  Awaited<ReturnType<typeof logoutBrowserSession>>
>;
export type LogoutBrowserSessionQueryError = ErrorType<void>;

/**
 * @summary Clear the session and begin OIDC logout
 */

export function useLogoutBrowserSession<
  TData = Awaited<ReturnType<typeof logoutBrowserSession>>,
  TError = ErrorType<void>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof logoutBrowserSession>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getLogoutBrowserSessionQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Exchange a mobile OIDC code for a session token
 */
export const getExchangeMobileAuthorizationCodeUrl = () => {
  return `/api/mobile-auth/token-exchange`;
};

export const exchangeMobileAuthorizationCode = async (
  mobileTokenExchangeRequest: MobileTokenExchangeRequest,
  options?: RequestInit,
): Promise<MobileTokenExchangeSuccess> => {
  return customFetch<MobileTokenExchangeSuccess>(
    getExchangeMobileAuthorizationCodeUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(mobileTokenExchangeRequest),
    },
  );
};

export const getExchangeMobileAuthorizationCodeMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof exchangeMobileAuthorizationCode>>,
    TError,
    { data: BodyType<MobileTokenExchangeRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof exchangeMobileAuthorizationCode>>,
  TError,
  { data: BodyType<MobileTokenExchangeRequest> },
  TContext
> => {
  const mutationKey = ["exchangeMobileAuthorizationCode"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof exchangeMobileAuthorizationCode>>,
    { data: BodyType<MobileTokenExchangeRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return exchangeMobileAuthorizationCode(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ExchangeMobileAuthorizationCodeMutationResult = NonNullable<
  Awaited<ReturnType<typeof exchangeMobileAuthorizationCode>>
>;
export type ExchangeMobileAuthorizationCodeMutationBody =
  BodyType<MobileTokenExchangeRequest>;
export type ExchangeMobileAuthorizationCodeMutationError = ErrorType<void>;

/**
 * @summary Exchange a mobile OIDC code for a session token
 */
export const useExchangeMobileAuthorizationCode = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof exchangeMobileAuthorizationCode>>,
    TError,
    { data: BodyType<MobileTokenExchangeRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof exchangeMobileAuthorizationCode>>,
  TError,
  { data: BodyType<MobileTokenExchangeRequest> },
  TContext
> => {
  return useMutation(
    getExchangeMobileAuthorizationCodeMutationOptions(options),
  );
};

/**
 * @summary Delete a mobile session token
 */
export const getLogoutMobileSessionUrl = () => {
  return `/api/mobile-auth/logout`;
};

export const logoutMobileSession = async (
  options?: RequestInit,
): Promise<LogoutSuccess> => {
  return customFetch<LogoutSuccess>(getLogoutMobileSessionUrl(), {
    ...options,
    method: "POST",
  });
};

export const getLogoutMobileSessionMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof logoutMobileSession>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof logoutMobileSession>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["logoutMobileSession"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof logoutMobileSession>>,
    void
  > = () => {
    return logoutMobileSession(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type LogoutMobileSessionMutationResult = NonNullable<
  Awaited<ReturnType<typeof logoutMobileSession>>
>;

export type LogoutMobileSessionMutationError = ErrorType<unknown>;

/**
 * @summary Delete a mobile session token
 */
export const useLogoutMobileSession = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof logoutMobileSession>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof logoutMobileSession>>,
  TError,
  void,
  TContext
> => {
  return useMutation(getLogoutMobileSessionMutationOptions(options));
};

/**
 * @summary Get current user profile
 */
export const getGetProfileUrl = () => {
  return `/api/profile`;
};

export const getProfile = async (
  options?: RequestInit,
): Promise<UserProfile> => {
  return customFetch<UserProfile>(getGetProfileUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetProfileQueryKey = () => {
  return [`/api/profile`] as const;
};

export const getGetProfileQueryOptions = <
  TData = Awaited<ReturnType<typeof getProfile>>,
  TError = ErrorType<void>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getProfile>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetProfileQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getProfile>>> = ({
    signal,
  }) => getProfile({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getProfile>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetProfileQueryResult = NonNullable<
  Awaited<ReturnType<typeof getProfile>>
>;
export type GetProfileQueryError = ErrorType<void>;

/**
 * @summary Get current user profile
 */

export function useGetProfile<
  TData = Awaited<ReturnType<typeof getProfile>>,
  TError = ErrorType<void>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getProfile>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetProfileQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Update current user profile
 */
export const getUpdateProfileUrl = () => {
  return `/api/profile`;
};

export const updateProfile = async (
  updateProfileBody: UpdateProfileBody,
  options?: RequestInit,
): Promise<UserProfile> => {
  return customFetch<UserProfile>(getUpdateProfileUrl(), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(updateProfileBody),
  });
};

export const getUpdateProfileMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateProfile>>,
    TError,
    { data: BodyType<UpdateProfileBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateProfile>>,
  TError,
  { data: BodyType<UpdateProfileBody> },
  TContext
> => {
  const mutationKey = ["updateProfile"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateProfile>>,
    { data: BodyType<UpdateProfileBody> }
  > = (props) => {
    const { data } = props ?? {};

    return updateProfile(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateProfileMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateProfile>>
>;
export type UpdateProfileMutationBody = BodyType<UpdateProfileBody>;
export type UpdateProfileMutationError = ErrorType<void>;

/**
 * @summary Update current user profile
 */
export const useUpdateProfile = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateProfile>>,
    TError,
    { data: BodyType<UpdateProfileBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof updateProfile>>,
  TError,
  { data: BodyType<UpdateProfileBody> },
  TContext
> => {
  return useMutation(getUpdateProfileMutationOptions(options));
};

/**
 * @summary Get today's usage count
 */
export const getGetUsageUrl = () => {
  return `/api/usage`;
};

export const getUsage = async (options?: RequestInit): Promise<UsageStatus> => {
  return customFetch<UsageStatus>(getGetUsageUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetUsageQueryKey = () => {
  return [`/api/usage`] as const;
};

export const getGetUsageQueryOptions = <
  TData = Awaited<ReturnType<typeof getUsage>>,
  TError = ErrorType<void>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getUsage>>, TError, TData>;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetUsageQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getUsage>>> = ({
    signal,
  }) => getUsage({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getUsage>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetUsageQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUsage>>
>;
export type GetUsageQueryError = ErrorType<void>;

/**
 * @summary Get today's usage count
 */

export function useGetUsage<
  TData = Awaited<ReturnType<typeof getUsage>>,
  TError = ErrorType<void>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getUsage>>, TError, TData>;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetUsageQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Increment today's post usage count
 */
export const getIncrementUsageUrl = () => {
  return `/api/usage/increment`;
};

export const incrementUsage = async (
  options?: RequestInit,
): Promise<UsageStatus> => {
  return customFetch<UsageStatus>(getIncrementUsageUrl(), {
    ...options,
    method: "POST",
  });
};

export const getIncrementUsageMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof incrementUsage>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof incrementUsage>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["incrementUsage"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof incrementUsage>>,
    void
  > = () => {
    return incrementUsage(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type IncrementUsageMutationResult = NonNullable<
  Awaited<ReturnType<typeof incrementUsage>>
>;

export type IncrementUsageMutationError = ErrorType<void>;

/**
 * @summary Increment today's post usage count
 */
export const useIncrementUsage = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof incrementUsage>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof incrementUsage>>,
  TError,
  void,
  TContext
> => {
  return useMutation(getIncrementUsageMutationOptions(options));
};

/**
 * @summary Upgrade to premium (demo mode)
 */
export const getUpgradePlanUrl = () => {
  return `/api/plan/upgrade`;
};

export const upgradePlan = async (
  options?: RequestInit,
): Promise<UserProfile> => {
  return customFetch<UserProfile>(getUpgradePlanUrl(), {
    ...options,
    method: "POST",
  });
};

export const getUpgradePlanMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof upgradePlan>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof upgradePlan>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["upgradePlan"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof upgradePlan>>,
    void
  > = () => {
    return upgradePlan(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpgradePlanMutationResult = NonNullable<
  Awaited<ReturnType<typeof upgradePlan>>
>;

export type UpgradePlanMutationError = ErrorType<void>;

/**
 * @summary Upgrade to premium (demo mode)
 */
export const useUpgradePlan = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof upgradePlan>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof upgradePlan>>,
  TError,
  void,
  TContext
> => {
  return useMutation(getUpgradePlanMutationOptions(options));
};

/**
 * @summary Downgrade to free plan (demo mode)
 */
export const getDowngradePlanUrl = () => {
  return `/api/plan/downgrade`;
};

export const downgradePlan = async (
  options?: RequestInit,
): Promise<UserProfile> => {
  return customFetch<UserProfile>(getDowngradePlanUrl(), {
    ...options,
    method: "POST",
  });
};

export const getDowngradePlanMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof downgradePlan>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof downgradePlan>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["downgradePlan"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof downgradePlan>>,
    void
  > = () => {
    return downgradePlan(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DowngradePlanMutationResult = NonNullable<
  Awaited<ReturnType<typeof downgradePlan>>
>;

export type DowngradePlanMutationError = ErrorType<void>;

/**
 * @summary Downgrade to free plan (demo mode)
 */
export const useDowngradePlan = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof downgradePlan>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof downgradePlan>>,
  TError,
  void,
  TContext
> => {
  return useMutation(getDowngradePlanMutationOptions(options));
};

/**
 * @summary Get AI-style help response
 */
export const getGetHelpUrl = () => {
  return `/api/help`;
};

export const getHelp = async (
  helpRequest: HelpRequest,
  options?: RequestInit,
): Promise<HelpResponse> => {
  return customFetch<HelpResponse>(getGetHelpUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(helpRequest),
  });
};

export const getGetHelpMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof getHelp>>,
    TError,
    { data: BodyType<HelpRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof getHelp>>,
  TError,
  { data: BodyType<HelpRequest> },
  TContext
> => {
  const mutationKey = ["getHelp"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof getHelp>>,
    { data: BodyType<HelpRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return getHelp(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type GetHelpMutationResult = NonNullable<
  Awaited<ReturnType<typeof getHelp>>
>;
export type GetHelpMutationBody = BodyType<HelpRequest>;
export type GetHelpMutationError = ErrorType<unknown>;

/**
 * @summary Get AI-style help response
 */
export const useGetHelp = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof getHelp>>,
    TError,
    { data: BodyType<HelpRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof getHelp>>,
  TError,
  { data: BodyType<HelpRequest> },
  TContext
> => {
  return useMutation(getGetHelpMutationOptions(options));
};

/**
 * @summary Delete the current user account
 */
export const getDeleteAccountUrl = () => {
  return `/api/account`;
};

export const deleteAccount = async (
  options?: RequestInit,
): Promise<LogoutSuccess> => {
  return customFetch<LogoutSuccess>(getDeleteAccountUrl(), {
    ...options,
    method: "DELETE",
  });
};

export const getDeleteAccountMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteAccount>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteAccount>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["deleteAccount"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteAccount>>,
    void
  > = () => {
    return deleteAccount(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteAccountMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteAccount>>
>;

export type DeleteAccountMutationError = ErrorType<void>;

/**
 * @summary Delete the current user account
 */
export const useDeleteAccount = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteAccount>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof deleteAccount>>,
  TError,
  void,
  TContext
> => {
  return useMutation(getDeleteAccountMutationOptions(options));
};
