/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export interface AuthUser {
  id: string;
  /** @nullable */
  email: string | null;
  /** @nullable */
  firstName: string | null;
  /** @nullable */
  lastName: string | null;
  /** @nullable */
  profileImageUrl: string | null;
}

export interface AuthUserEnvelope {
  user: AuthUser | null;
}

export interface MobileTokenExchangeRequest {
  /** @minLength 1 */
  code: string;
  /** @minLength 1 */
  code_verifier: string;
  /** @minLength 1 */
  redirect_uri: string;
  /** @minLength 1 */
  state: string;
  /** @minLength 1 */
  nonce?: string;
}

export interface MobileTokenExchangeSuccess {
  token: string;
}

export const LogoutSuccessValue = {
  success: true,
} as const;
export type LogoutSuccess = typeof LogoutSuccessValue;

export interface ErrorEnvelope {
  error: string;
}

export type UserProfilePlanTier =
  (typeof UserProfilePlanTier)[keyof typeof UserProfilePlanTier];

export const UserProfilePlanTier = {
  free: "free",
  premium: "premium",
} as const;

export interface UserProfile {
  userId: string;
  planTier: UserProfilePlanTier;
  /** @nullable */
  displayName: string | null;
  /** @nullable */
  email: string | null;
  /** @nullable */
  firstName: string | null;
  /** @nullable */
  lastName: string | null;
  /** @nullable */
  profileImageUrl: string | null;
}

export interface UpdateProfileBody {
  displayName?: string;
}

export type UsageStatusPlanTier =
  (typeof UsageStatusPlanTier)[keyof typeof UsageStatusPlanTier];

export const UsageStatusPlanTier = {
  free: "free",
  premium: "premium",
} as const;

export interface UsageStatus {
  postsUsed: number;
  planTier: UsageStatusPlanTier;
  limitReached: boolean;
}

export interface HelpRequest {
  question: string;
}

export interface HelpResponse {
  answer: string;
}

/**
 * Opaque session token — `Bearer <sid>`.
 */
export type AuthorizationSessionHeaderParameter = string;

export type BeginBrowserLoginParams = {
  returnTo?: string;
};

export type HandleBrowserLoginCallbackParams = {
  code?: string;
  state?: string;
  iss?: string;
};
