/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import type { UserProfilePlanTier } from "./userProfilePlanTier";

export interface UserProfile {
  userId: string;
  planTier: UserProfilePlanTier;
  /** @nullable */
  displayName: string | null;
  /** @nullable */
  email: string | null;
  /** @nullable */
  firstName: string | null;
  /** @nullable */
  lastName: string | null;
  /** @nullable */
  profileImageUrl: string | null;
}
